apiVersion: trainwithshubham.com/v1
kind: DevopsBatch

metadata:
  name: junoon-batch-9

spec:
  name: Devops-zero to hero junoon batch 9
  duration: "3 month from 25th january 2025"
  platform: trainwithshubham.com
  mode: "live as always"
